### ISSUE TITLE
error with DB and HammerDB scripts

### ISSUE THREAD

**Issue by Arkaikus** [josanabr/articulo_ds_2021_I#21]
- `PostgreSQL/inst-PostgreSQL.sh` missing *-y* flag in line 7: `sudo apt install postgres postgresql-contrib`

- `HammedDB/inst-HammerDB.sh` installation script doesn't register **hammerdbcli** to path, executing `cd /root/HammerDB && sh pruebaPostgreSQL-HDB.sh` or `pruebaMySQL-HDB.sh` gives not found error

- executing tests awaits user input
- some kind of syntax error in SQL query for postrgres

![image](https://user-images.githubusercontent.com/25040293/119072096-8d3e8700-b9b0-11eb-9b92-dd0cc6a006e0.png)

**Comment by aledark** [comment]
Hola Santiago, te doy respuesta de los issues:

- El script de instalación de postgres es general y así funciona en baremetal, si te pide más argumentos tal vez sea algo propio del SO. Así que agradeceria si lo modificas localmente con el flag que necesita y así no afectar a los demás compañeros.
- Por fa, fijate en las instrucciones que se colocaron en el word compartido. Allí se indica que despues de la instalación aparecerá una carpeta llamada HAMMERDB-4.1, adentro se encuentra el **hammerdbcli** que no encuentras en la raiz. La idea es que muevas allí los scripts necesarios que se encuentran en este repositorio en la seccion de **codigo/HammerDB** y luego si ejecutes el sh... 
-  Ya hice el commit con la correción de la query 

Si esto no soluciona los problemas, comenta de nuevo y si algo podemos concertar una reunión,

Saludos

**Comment by Arkaikus** [comment]
Hola Maria

- Respecto a lo del flag si se quiere hacer de forma automatizada si es recomendable ponerlo al igual que con la instalación de mysql, mucho mas si hay algunos pocos casos donde se pide la confirmación

- Confirmo que se descarga HammerDB donde se ejecuta **inst-HammerDB.sh** en la carpeta **HammerDB-1.4**, pero no es tan evidente copiar los scripts de prueba a la carpeta de instalación donde se encuentra el ejecutable para poder correr las pruebas y según veo, revisando el archivo **hammerdbcli**, si es necesario hacerlo. Esto vale la pena dejarlo documentado en un readme.md

- Incluso otra alternativa podría ser descomprimir el .tar.gz en la misma carpeta donde están todos los scripts cuando se ejecuta **inst-HammerDB.sh** para evitarse ese paso de volver a copiar y así poder correr las pruebas sin problemas

Saludos
